name: pluginCensura
version: '1.0.0-SNAPSHOT'
main: br.plugins.PluginCensura
description: Plugin simples para censurar palavroes no chat.
permissions:
  plugincensura.bypass:
    description: Admin/ops recebem bypass contra a censura.
    default: op
